DROP TABLE IF EXISTS catalog_medical;
CREATE TABLE catalog_medical (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_medical_barcode ON catalog_medical(barcode);

DROP TABLE IF EXISTS catalog_kirana_stores;
CREATE TABLE catalog_kirana_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_kirana_stores_barcode ON catalog_kirana_stores(barcode);

DROP TABLE IF EXISTS catalog_electronics_stores;
CREATE TABLE catalog_electronics_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_electronics_stores_barcode ON catalog_electronics_stores(barcode);

DROP TABLE IF EXISTS catalog_clothing_boutiques;
CREATE TABLE catalog_clothing_boutiques (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_clothing_boutiques_barcode ON catalog_clothing_boutiques(barcode);

DROP TABLE IF EXISTS catalog_footwear_stores;
CREATE TABLE catalog_footwear_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_footwear_stores_barcode ON catalog_footwear_stores(barcode);

DROP TABLE IF EXISTS catalog_stationery_shops;
CREATE TABLE catalog_stationery_shops (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_stationery_shops_barcode ON catalog_stationery_shops(barcode);

DROP TABLE IF EXISTS catalog_toy_stores;
CREATE TABLE catalog_toy_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_toy_stores_barcode ON catalog_toy_stores(barcode);

DROP TABLE IF EXISTS catalog_pet_supply_stores;
CREATE TABLE catalog_pet_supply_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_pet_supply_stores_barcode ON catalog_pet_supply_stores(barcode);

DROP TABLE IF EXISTS catalog_home_decor_stores;
CREATE TABLE catalog_home_decor_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_home_decor_stores_barcode ON catalog_home_decor_stores(barcode);

DROP TABLE IF EXISTS catalog_cosmetics_stores;
CREATE TABLE catalog_cosmetics_stores (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_cosmetics_stores_barcode ON catalog_cosmetics_stores(barcode);

DROP TABLE IF EXISTS catalog_other;
CREATE TABLE catalog_other (
  product_uuid TEXT PRIMARY KEY,
  category TEXT,
  procurement_template TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_photo TEXT,
  brand TEXT,
  parent_sku TEXT,
  barcode TEXT,
  hsn_code TEXT,
  tax_percentage REAL,
  cost_price REAL,
  mrp REAL,
  selling_price REAL,
  opening_stock REAL,
  reorder_level REAL,
  variant_attr_1_name TEXT,
  variant_attr_1_value TEXT,
  variant_attr_2_name TEXT,
  variant_attr_2_value TEXT,
  batch_number TEXT,
  mfg_date TEXT,
  expiry_date TEXT,
  base_uom TEXT,
  packaging_uom TEXT,
  conversion_factor REAL,
  serial_imei_number TEXT,
  service_duration_mins INTEGER,
  staff_commission_pct REAL
);
CREATE INDEX idx_catalog_other_barcode ON catalog_other(barcode);

CREATE TABLE user_deletion_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT UNIQUE NOT NULL,
  requested_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  processed_at TEXT,
  error_message TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_deletion_requests_status ON user_deletion_requests(status);
CREATE INDEX idx_user_deletion_requests_user_id ON user_deletion_requests(user_id);

