// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcEFA85ub-wrK6WlFRwWJZN2anRUXhYg',
    appId: '1:412357819576:web:dfeb84b318db68118a084d',
    messagingSenderId: '412357819576',
    projectId: 'orushops-110',
    authDomain: 'orushops-110.firebaseapp.com',
    storageBucket: 'orushops-110.firebasestorage.app',
    measurementId: 'G-EBGTF3KP2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aPMD23kKoOe3aCI5HEG5MgxXRJ21hZg',
    appId: '1:412357819576:android:a06eeee71561b5178a084d',
    messagingSenderId: '412357819576',
    projectId: 'orushops-110',
    storageBucket: 'orushops-110.firebasestorage.app',
  );

}